In [3]:
import numpy as np
import pandas as pd
 
u = np.array([2, 4, 7, 5, 9, 10, 16])
print(u[0])
print(u[2])
print(u[4])

2
7
9


C:\Users\jecip\AppData\Local\Temp\ipykernel_23408\2965159621.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
print(u)

[ 2  4  7  5  9 10 16]


In [9]:
import numpy as np 

revenue = np.array([[180, 240,120],[200, 360,180], [220, 400, 200]])
expenses = np.array([[80, 10, 8], [90, 16,10], [100, 20,10]])

profit= revenue-expenses
print(profit)

[[100 230 112]
 [110 344 170]
 [120 380 190]]


In [15]:
import numpy as np 
units = np.array ([[50, 60 ,25],[10, 13, 5],[40, 70, 52]])
priceperunit = np.array([20, 30, 15])
totalunits = units*priceperunit



In [16]:
print(totalunits)

[[1000 1800  375]
 [ 200  390   75]
 [ 800 2100  780]]


In [12]:
import numpy as np

units = np.array([[50, 60, 25],
                  [10, 13, 5],
                  [40, 70, 52]])

priceperunit = np.array([20, 30, 15])
totalunits = units * priceperunit

In [17]:
print(totalunits)

[[1000 1800  375]
 [ 200  390   75]
 [ 800 2100  780]]


In [20]:
priceperunit=np.array([20,30,15])
units=np.array([[50,60,25],[10,13,5],[40,70,52]])
totalsales=np.dot(priceperunit,units)
totalsales

array([1900, 2640, 1430])